import type { CookingExpansionBatch, CookingExpansionRow } from "./types";
import { COOKING_EXPANSION_BATCH_01 } from "./batch01";
import { COOKING_EXPANSION_BATCH_02 } from "./batch02";
import { COOKING_EXPANSION_BATCH_03 } from "./batch03";
import { COOKING_EXPANSION_BATCH_04 } from "./batch04";
import { COOKING_EXPANSION_BATCH_05 } from "./batch05";
import { COOKING_EXPANSION_BATCH_06 } from "./batch06";
import { COOKING_EXPANSION_BATCH_07 } from "./batch07";
import { COOKING_EXPANSION_BATCH_08 } from "./batch08";
import { COOKING_EXPANSION_BATCH_09 } from "./batch09";
import { COOKING_EXPANSION_BATCH_10 } from "./batch10";
import { COOKING_EXPANSION_BATCH_11 } from "./batch11";
import { COOKING_EXPANSION_BATCH_12 } from "./batch12";
import { COOKING_EXPANSION_BATCH_13 } from "./batch13";
import { COOKING_EXPANSION_BATCH_14 } from "./batch14";
import { COOKING_EXPANSION_BATCH_15 } from "./batch15";
import { COOKING_EXPANSION_BATCH_16 } from "./batch16";
import { COOKING_EXPANSION_BATCH_17 } from "./batch17";
import { COOKING_EXPANSION_BATCH_18 } from "./batch18";
import { COOKING_EXPANSION_BATCH_19 } from "./batch19";
import { COOKING_EXPANSION_BATCH_20 } from "./batch20";
import { COOKING_EXPANSION_BATCH_21 } from "./batch21";
import { COOKING_EXPANSION_BATCH_22 } from "./batch22";
import { COOKING_EXPANSION_BATCH_23 } from "./batch23";
import { COOKING_EXPANSION_BATCH_24 } from "./batch24";
import { COOKING_EXPANSION_BATCH_25 } from "./batch25";
import { COOKING_EXPANSION_BATCH_26 } from "./batch26";
import { COOKING_EXPANSION_BATCH_27 } from "./batch27";
import { COOKING_EXPANSION_BATCH_28 } from "./batch28";
import { COOKING_EXPANSION_BATCH_29 } from "./batch29";
import { COOKING_EXPANSION_BATCH_30 } from "./batch30";
import { COOKING_EXPANSION_BATCH_31 } from "./batch31";
import { COOKING_EXPANSION_BATCH_32 } from "./batch32";
import { COOKING_EXPANSION_BATCH_33 } from "./batch33";
import { COOKING_EXPANSION_BATCH_34 } from "./batch34";
import { COOKING_EXPANSION_BATCH_35 } from "./batch35";
import { COOKING_EXPANSION_BATCH_36 } from "./batch36";
import { COOKING_EXPANSION_BATCH_37 } from "./batch37";
import { COOKING_EXPANSION_BATCH_38 } from "./batch38";

export const COOKING_EXPANSION_BATCHES: readonly CookingExpansionBatch[] = [
  COOKING_EXPANSION_BATCH_01,
  COOKING_EXPANSION_BATCH_02,
  COOKING_EXPANSION_BATCH_03,
  COOKING_EXPANSION_BATCH_04,
  COOKING_EXPANSION_BATCH_05,
  COOKING_EXPANSION_BATCH_06,
  COOKING_EXPANSION_BATCH_07,
  COOKING_EXPANSION_BATCH_08,
  COOKING_EXPANSION_BATCH_09,
  COOKING_EXPANSION_BATCH_10,
  COOKING_EXPANSION_BATCH_11,
  COOKING_EXPANSION_BATCH_12,
  COOKING_EXPANSION_BATCH_13,
  COOKING_EXPANSION_BATCH_14,
  COOKING_EXPANSION_BATCH_15,
  COOKING_EXPANSION_BATCH_16,
  COOKING_EXPANSION_BATCH_17,
  COOKING_EXPANSION_BATCH_18,
  COOKING_EXPANSION_BATCH_19,
  COOKING_EXPANSION_BATCH_20,
  COOKING_EXPANSION_BATCH_21,
  COOKING_EXPANSION_BATCH_22,
  COOKING_EXPANSION_BATCH_23,
  COOKING_EXPANSION_BATCH_24,
  COOKING_EXPANSION_BATCH_25,
  COOKING_EXPANSION_BATCH_26,
  COOKING_EXPANSION_BATCH_27,
  COOKING_EXPANSION_BATCH_28,
  COOKING_EXPANSION_BATCH_29,
  COOKING_EXPANSION_BATCH_30,
  COOKING_EXPANSION_BATCH_31,
  COOKING_EXPANSION_BATCH_32,
  COOKING_EXPANSION_BATCH_33,
  COOKING_EXPANSION_BATCH_34,
  COOKING_EXPANSION_BATCH_35,
  COOKING_EXPANSION_BATCH_36,
  COOKING_EXPANSION_BATCH_37,
  COOKING_EXPANSION_BATCH_38,
];

export const COOKING_EXPANSION_ROWS: readonly CookingExpansionRow[] =
  COOKING_EXPANSION_BATCHES.flatMap((batch) => batch.rows);
